/*
    This query returns all courses for the current school year, for all schools, and lists what
    rubric definitions and transcript definitions they have attached to them.
*/

SELECT
	MSS_DISTRICT_SCHOOL_YEAR_CONTEXT.CTX_SCHOOL_YEAR,
	MSS_SCHOOL.SKL_SCHOOL_NAME,
	MSS_COURSE.CRS_SHORT_DESCRIPTION,
	MSS_COURSE_SCHOOL.CSK_COURSE_NUMBER,
	MSS_COURSE_SCHOOL.CSK_COURSE_DESCRIPTION,
	MSS_COURSE_SCHOOL.CSK_SHORT_DESCRIPTION,
	MSS_COURSE_SCHOOL.CSK_RBD_OID as RubricDefID,
	MSS_RUBRIC_DEFINITION.RBD_NAME as RubricDefinition,
	MSS_COURSE_SCHOOL.CSK_GTD_OID as TransDefId,
	MSS_GRADE_TRANSCRIPT_DEFINITION.GTD_NAME as TranscriptDefinition
FROM
	MSS_SCHOOL
	LEFT OUTER JOIN MSS_COURSE_SCHOOL ON MSS_SCHOOL.SKL_OID=MSS_COURSE_SCHOOL.CSK_SKL_OID
	LEFT OUTER JOIN MSS_COURSE ON MSS_COURSE_SCHOOL.CSK_CRS_OID=MSS_COURSE.CRS_OID
	LEFT OUTER JOIN MSS_DISTRICT_SCHOOL_YEAR_CONTEXT ON MSS_COURSE.CRS_CTX_OID=MSS_DISTRICT_SCHOOL_YEAR_CONTEXT.CTX_OID
	LEFT OUTER JOIN MSS_RUBRIC_DEFINITION ON MSS_COURSE_SCHOOL.CSK_RBD_OID=MSS_RUBRIC_DEFINITION.RBD_OID
	LEFT OUTER JOIN MSS_GRADE_TRANSCRIPT_DEFINITION ON MSS_COURSE_SCHOOL.CSK_GTD_OID=MSS_GRADE_TRANSCRIPT_DEFINITION.GTD_OID
WHERE
	MSS_SCHOOL.SKL_INACTIVE_IND = 0
	AND MSS_DISTRICT_SCHOOL_YEAR_CONTEXT.CTX_FIELDA_001 = 'Current'
ORDER BY
	MSS_SCHOOL.SKL_SCHOOL_NAME,
	MSS_COURSE.CRS_SHORT_DESCRIPTION ASC

