SELECT
	MSS_SCHOOL.SKL_SCHOOL_ID as SchoolId,
	MSS_SCHEDULE_MASTER.MST_OID as SectionId,	
	MSS_STUDENT.STD_ID_LOCAL as StudentNumber
FROM
	MSS_STUDENT_SCHEDULE
	LEFT OUTER JOIN MSS_STUDENT ON MSS_STUDENT_SCHEDULE.SSC_STD_OID=MSS_STUDENT.STD_OID
	LEFT OUTER JOIN MSS_SCHEDULE_MASTER ON MSS_STUDENT_SCHEDULE.SSC_MST_OID=MSS_SCHEDULE_MASTER.MST_OID
	LEFT OUTER JOIN MSS_SCHEDULE ON MSS_SCHEDULE_MASTER.MST_SCH_OID=MSS_SCHEDULE.SCH_OID
	LEFT OUTER JOIN MSS_SCHOOL ON MSS_SCHEDULE.SCH_SKL_OID=MSS_SCHOOL.SKL_OID
WHERE
	MSS_STUDENT.STD_ENROLLMENT_STATUS IN ('Active', 'Active No Primary')