WITH RankedTeachers AS (
	SELECT
		MTC_MST_OID,
		MSS_STAFF.STF_ID_LOCAL,
		ROW_NUMBER() OVER (PARTITION BY MTC_MST_OID ORDER BY MTC_PRIMARY_TEACHER_IND DESC, MTC_OID) as teacher_rank
	FROM 
		MSS_SCHEDULE_MASTER_TEACHER
		LEFT OUTER JOIN MSS_STAFF ON MSS_SCHEDULE_MASTER_TEACHER.MTC_STF_OID=MSS_STAFF.STF_OID
)
SELECT
	MSS_SCHEDULE_MASTER.MST_OID,
	MSS_SCHEDULE_TERM_DATE.TMD_END_DATE as TermEnd,
	MSS_SCHOOL.SKL_SCHOOL_ID as SchoolId,
	t1.STF_ID_LOCAL as Teacher1,
	t2.STF_ID_LOCAL as Teacher2,
	t3.STF_ID_LOCAL as Teacher3,
	MSS_SCHEDULE_TERM.TRM_TERM_NAME as TermName,
	MSS_SCHEDULE_MASTER.MST_OID as SectionId,
	MSS_SCHEDULE_TERM_DATE.TMD_START_DATE as TermStart,
	MSS_SCHEDULE_MASTER.MST_DESCRIPTION as CourseName,
	MSS_COURSE_SCHOOL.CSK_COURSE_NUMBER as CourseNumber, 
	MSS_SCHEDULE_MASTER.MST_SECTION_NUMBER as SectionNumber,
	MSS_SCHEDULE_MASTER.MST_DESCRIPTION as CourseDescription
FROM
	MSS_SCHEDULE_MASTER
	LEFT OUTER JOIN MSS_SCHEDULE ON MSS_SCHEDULE_MASTER.MST_SCH_OID=MSS_SCHEDULE.SCH_OID
	LEFT OUTER JOIN MSS_SCHOOL ON MSS_SCHEDULE.SCH_SKL_OID=MSS_SCHOOL.SKL_OID	
	LEFT OUTER JOIN MSS_SCHEDULE_TERM ON MSS_SCHEDULE_MASTER.MST_TRM_OID=MSS_SCHEDULE_TERM.TRM_OID
	LEFT OUTER JOIN MSS_SCHEDULE_TERM_DATE ON MSS_SCHEDULE_TERM.TRM_OID=MSS_SCHEDULE_TERM_DATE.TMD_TRM_OID		
	LEFT OUTER JOIN MSS_COURSE_SCHOOL ON MSS_SCHEDULE_MASTER.MST_CSK_OID=MSS_COURSE_SCHOOL.CSK_OID
	LEFT OUTER JOIN MSS_DISTRICT_SCHOOL_YEAR_CONTEXT ON MSS_SCHEDULE.SCH_CTX_OID=MSS_DISTRICT_SCHOOL_YEAR_CONTEXT.CTX_OID
	LEFT OUTER JOIN RankedTeachers t1 ON MSS_SCHEDULE_MASTER.MST_OID=t1.MTC_MST_OID AND t1.teacher_rank=1
	LEFT OUTER JOIN RankedTeachers t2 ON MSS_SCHEDULE_MASTER.MST_OID=t2.MTC_MST_OID AND t2.teacher_rank=2
	LEFT OUTER JOIN RankedTeachers t3 ON MSS_SCHEDULE_MASTER.MST_OID=t3.MTC_MST_OID AND t3.teacher_rank=3
WHERE
	MSS_DISTRICT_SCHOOL_YEAR_CONTEXT.CTX_FIELDA_001 = 'Current'
	AND MSS_COURSE_SCHOOL.CSK_COURSE_NUMBER NOT IN ('FASA', 'NAC')
	AND MSS_SCHEDULE_TERM_DATE.TMD_END_DATE IS NOT NULL
ORDER BY TermEnd DESC;