SELECT 
	MSS_PERSON.PSN_EMAIL_01 as Email,
	MSS_CONTACT.CNT_OID as ExtId,
	MSS_PERSON.PSN_PHONE_01 as Phone,
	CONCAT(MSS_PERSON.PSN_NAME_FIRST, ' ', MSS_PERSON.PSN_NAME_LAST) as FullName,
	'Primary' as PhoneType,
	MSS_STUDENT_CONTACT.CTJ_RELATIONSHIP_CODE as Relationship,
	MSS_STUDENT.STD_ID_LOCAL as StudentNumber
FROM
	MSS_STUDENT_CONTACT
	LEFT OUTER JOIN MSS_CONTACT ON MSS_STUDENT_CONTACT.CTJ_CNT_OID=MSS_CONTACT.CNT_OID
	LEFT OUTER JOIN MSS_PERSON ON MSS_CONTACT.CNT_PSN_OID=MSS_PERSON.PSN_OID
	LEFT OUTER JOIN MSS_STUDENT ON MSS_STUDENT_CONTACT.CTJ_STD_OID=MSS_STUDENT.STD_OID
WHERE
	MSS_STUDENT.STD_ENROLLMENT_STATUS IN ('Active', 'Active No Primary')