SELECT
	STD_ID_LOCAL,
	CONCAT(MSS_PERSON.PSN_NAME_FIRST, ' ', MSS_PERSON.PSN_NAME_LAST) as Name,
	MSS_PERSON.PSN_EMAIL_01,
	ROW_NUMBER() OVER(PARTITION BY STD_ID_LOCAL ORDER BY CTJ_EMERGENCY_PRIORITY) as ContactNum,
	MSS_STUDENT_CONTACT.CTJ_RELATIONSHIP_CODE	
INTO #LSSD202_TEMP_STUCONTACTS
FROM
	MSS_STUDENT
	LEFT OUTER JOIN MSS_STUDENT_CONTACT ON MSS_STUDENT.STD_OID=MSS_STUDENT_CONTACT.CTJ_STD_OID
	LEFT OUTER JOIN MSS_CONTACT ON MSS_STUDENT_CONTACT.CTJ_CNT_OID=MSS_CONTACT.CNT_OID
	LEFT OUTER JOIN MSS_PERSON ON MSS_CONTACT.CNT_PSN_OID=MSS_PERSON.PSN_OID
WHERE 
	MSS_STUDENT.STD_ENROLLMENT_STATUS = 'Active'
	AND MSS_STUDENT_CONTACT.CTJ_FIELDA_001 = 1
;

SELECT
	MSS_STUDENT.STD_ID_LOCAL,
	MSS_STUDENT.STD_GRADE_LEVEL,
	Contact1.Name,
	Contact1.PSN_EMAIL_01,
	Contact1.CTJ_RELATIONSHIP_CODE,
	Contact2.Name,
	Contact2.PSN_EMAIL_01,
	Contact2.CTJ_RELATIONSHIP_CODE
FROM
	MSS_STUDENT
	LEFT OUTER JOIN #LSSD202_TEMP_STUCONTACTS as Contact1 ON MSS_STUDENT.STD_ID_LOCAL=Contact1.STD_ID_LOCAL AND Contact1.ContactNum = 1
	LEFT OUTER JOIN #LSSD202_TEMP_STUCONTACTS as Contact2 ON MSS_STUDENT.STD_ID_LOCAL=Contact2.STD_ID_LOCAL AND Contact2.ContactNum = 2
WHERE 
	MSS_STUDENT.STD_ID_LOCAL IN ( PUPIL, NUMBERS, GO, HERE)

DROP TABLE IF EXISTS #LSSD202_TEMP_STUCONTACTS;
